# ---------------------------------------------------------------------------
# Author: Kuan-Hao Chao <kuanhao.chao@gmail.com>
# Copyright 2026 Kuan-Hao Chao
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------
"""API parity against the frozen gffutils oracle.

Reads the committed manifest (``gffutils_manifest.json``, generated by
``tools/gen_parity_manifest.py`` from gffutils commit ``6b84330``) and checks
gffbase's public surface against it. Every difference must be declared in
``deviations.toml``.

The register is enforced in *both* directions, which is what stops it rotting:

* an undeclared gap fails, so surface cannot go missing silently;
* a stale declaration fails, so an entry cannot outlive the work it describes.

These tests need no gffutils installed -- the manifest is committed data.
"""

from __future__ import annotations

import importlib
import inspect
import json
from pathlib import Path

import pytest
import tomllib

#: These compare against the recorded manifest rather than a live gffutils, so
#: they run without the oracle installed. They still belong to the parity
#: group: `pytest -m parity` is the command a contributor runs to check
#: compatibility, and this file was silently absent from it.
pytestmark = pytest.mark.parity

HERE = Path(__file__).resolve().parent
MANIFEST_PATH = HERE / "gffutils_manifest.json"
DEVIATIONS_PATH = HERE / "deviations.toml"

VALID_STATUSES = {"planned", "intentional", "excluded"}


def _load_manifest() -> dict:
    if not MANIFEST_PATH.is_file():
        pytest.skip(f"parity manifest missing: {MANIFEST_PATH}")
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def _load_deviations() -> dict[str, dict]:
    if not DEVIATIONS_PATH.is_file():
        pytest.skip(f"deviations register missing: {DEVIATIONS_PATH}")
    raw = tomllib.loads(DEVIATIONS_PATH.read_text(encoding="utf-8"))
    return {entry["name"]: entry for entry in raw.get("deviation", [])}


MANIFEST = _load_manifest()
DEVIATIONS = _load_deviations()


def _gffbase_name(gffutils_module: str) -> str:
    return gffutils_module.replace("gffutils", "gffbase", 1)


def _import_or_none(name: str):
    try:
        return importlib.import_module(name)
    except ImportError:
        return None


# ---------------------------------------------------------------------------
# The register itself must be well-formed.
# ---------------------------------------------------------------------------


def test_every_deviation_is_well_formed():
    problems = []
    for name, entry in DEVIATIONS.items():
        status = entry.get("status")
        if status not in VALID_STATUSES:
            problems.append(f"{name}: status {status!r} not in {sorted(VALID_STATUSES)}")
        if entry.get("kind") not in {"module", "symbol", "signature"}:
            problems.append(f"{name}: kind {entry.get('kind')!r} is not module/symbol/signature")
        if status == "planned" and not entry.get("phase"):
            problems.append(f"{name}: status='planned' must name the delivering phase")
        if status == "intentional" and not entry.get("reason"):
            problems.append(f"{name}: status='intentional' must give a reason")
        if status == "excluded" and not entry.get("reason"):
            problems.append(f"{name}: status='excluded' must give a reason")
    assert not problems, "malformed deviations:\n  " + "\n  ".join(problems)


def test_manifest_records_the_pinned_oracle():
    """The manifest must be traceable to an exact commit.

    `gffutils.__version__` is not usable for this: `gffutils/version.py` reads
    installed distribution metadata first, so a source checkout reports
    whatever unrelated copy happens to be installed.
    """
    oracle = MANIFEST["oracle"]
    assert oracle["commit"] == "6b84330f472dd2b4c69e36f319da7ade95bd5961", (
        f"manifest was generated against {oracle['commit']}, not the pinned oracle"
    )


# ---------------------------------------------------------------------------
# Modules.
# ---------------------------------------------------------------------------

_MODULES = sorted(m for m, info in MANIFEST["modules"].items() if info.get("importable"))


@pytest.mark.parametrize("gffutils_module", _MODULES)
def test_module_exists_or_is_declared(gffutils_module):
    target = _gffbase_name(gffutils_module)
    mod = _import_or_none(target)
    entry = DEVIATIONS.get(target)

    if mod is not None:
        assert entry is None or entry.get("kind") != "module", (
            f"{target} is importable, but deviations.toml still declares it "
            f"{entry.get('status')!r}. Delete the stale entry."
        )
        return

    assert entry is not None, (
        f"{target} does not exist and is not declared in deviations.toml.\n"
        f"The oracle's {gffutils_module} exports "
        f"{sorted(MANIFEST['modules'][gffutils_module]['symbols'])}."
    )


# ---------------------------------------------------------------------------
# Symbols.
# ---------------------------------------------------------------------------


def _symbol_cases():
    for gffutils_module, info in sorted(MANIFEST["modules"].items()):
        if not info.get("importable"):
            continue
        target = _gffbase_name(gffutils_module)
        # A module declared missing accounts for all of its symbols; listing
        # each one again would be noise.
        if target in DEVIATIONS and DEVIATIONS[target].get("kind") == "module":
            continue
        for symbol in sorted(info["symbols"]):
            yield pytest.param(target, symbol, id=f"{target}.{symbol}")


@pytest.mark.parametrize(("target_module", "symbol"), list(_symbol_cases()))
def test_symbol_exists_or_is_declared(target_module, symbol):
    mod = _import_or_none(target_module)
    if mod is None:
        pytest.skip(f"{target_module} absent (covered by its own module-level deviation)")

    qualified = f"{target_module}.{symbol}"
    entry = DEVIATIONS.get(qualified)

    if hasattr(mod, symbol):
        assert entry is None or entry.get("status") == "intentional", (
            f"{qualified} exists, but deviations.toml declares it "
            f"{entry.get('status')!r}. Delete the stale entry."
        )
        return

    assert entry is not None, (
        f"{qualified} is missing and undeclared. Either implement it or add a "
        f"deviations.toml entry saying why not."
    )


# ---------------------------------------------------------------------------
# Signatures of the surface that does exist.
# ---------------------------------------------------------------------------


def _implemented_callables():
    """(module, symbol) pairs present in BOTH the oracle manifest and gffbase."""
    for gffutils_module, info in sorted(MANIFEST["modules"].items()):
        if not info.get("importable"):
            continue
        target = _gffbase_name(gffutils_module)
        mod = _import_or_none(target)
        if mod is None:
            continue
        for symbol, desc in sorted(info["symbols"].items()):
            if desc.get("kind") not in {"function", "class"}:
                continue
            if not desc.get("signature"):
                continue
            if not hasattr(mod, symbol):
                continue
            yield pytest.param(target, symbol, desc, id=f"{target}.{symbol}")


@pytest.mark.parametrize(("target_module", "symbol", "desc"), list(_implemented_callables()))
def test_callable_accepts_every_oracle_parameter(target_module, symbol, desc):
    """Every parameter the oracle accepts must be accepted here too.

    This is deliberately one-directional: gffbase may add parameters the oracle
    never had. What it may not do is reject a call that the oracle accepts,
    which is exactly what a drop-in replacement promises.
    """
    mod = importlib.import_module(target_module)
    obj = getattr(mod, symbol)
    try:
        ours = inspect.signature(obj)
    except (TypeError, ValueError):
        pytest.skip(f"{symbol} has no introspectable signature")

    accepts_kwargs = any(p.kind is inspect.Parameter.VAR_KEYWORD for p in ours.parameters.values())
    missing = []
    for param in desc["signature"]["parameters"]:
        name = param["name"]
        if name in {"self", "cls"} or param["kind"] in {"VAR_POSITIONAL", "VAR_KEYWORD"}:
            continue
        if name in ours.parameters:
            continue
        if accepts_kwargs:
            # Swallowed by **kwargs. Accepting-and-ignoring is its own defect,
            # but it is a behavioural one -- the differential tests catch it,
            # not this structural check.
            continue
        missing.append(name)

    qualified = f"{target_module}.{symbol}"
    entry = DEVIATIONS.get(qualified)
    if missing and entry is not None and entry.get("kind") == "signature":
        pytest.skip(f"declared signature deviation: {entry.get('reason', '')[:80]}")

    assert not missing, (
        f"{qualified} rejects parameters the oracle accepts: {missing}\n"
        f"oracle signature: ({', '.join(p['name'] for p in desc['signature']['parameters'])})\n"
        f"ours:             {ours}"
    )


# ---------------------------------------------------------------------------
# Scoreboard. Not an assertion -- a always-visible progress readout.
# ---------------------------------------------------------------------------


def test_report_parity_scoreboard(capsys):
    total = present = 0
    missing_modules = []
    missing_symbols = []

    for gffutils_module, info in sorted(MANIFEST["modules"].items()):
        if not info.get("importable"):
            continue
        target = _gffbase_name(gffutils_module)
        mod = _import_or_none(target)
        if mod is None:
            missing_modules.append(target)
            total += len(info["symbols"])
            continue
        for symbol in sorted(info["symbols"]):
            total += 1
            if hasattr(mod, symbol):
                present += 1
            else:
                missing_symbols.append(f"{target}.{symbol}")

    pct = 100.0 * present / total if total else 100.0
    with capsys.disabled():
        print(
            f"\n  gffutils parity: {present}/{total} symbols ({pct:.1f}%)"
            f" | {len(missing_modules)} modules and"
            f" {len(missing_symbols)} symbols outstanding"
        )

    # Everything outstanding must be accounted for; the count itself is
    # progress, not a gate.
    undeclared = [
        name
        for name in missing_modules + missing_symbols
        if name not in DEVIATIONS
        and not any(name.startswith(m + ".") for m in missing_modules if m in DEVIATIONS)
    ]
    assert not undeclared, f"undeclared parity gaps: {undeclared}"
