#!/usr/bin/env bash
# clean_workspace.sh — safe deep-clean of the gffbase workspace.
#
# Removes only generated artifacts (caches, build outputs, render
# trees, benchmark outputs) — every path in this script is also listed
# in `.gitignore`, so no tracked file can be touched. Idempotent: safe
# to re-run on an already-clean tree.
#
# Usage: bash clean_workspace.sh

set -euo pipefail

# Anchor to the script's directory; an accidental `cd` elsewhere must
# not put `rm -rf` on the wrong tree.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Sanity check: refuse to run if this isn't the gffbase repo root.
if [[ ! -f "pyproject.toml" || ! -d "rust" || ! -d "python/gffbase" ]]; then
  echo "Refusing to run: $ROOT does not look like the gffbase repo root." >&2
  exit 1
fi

echo "==> Cleaning workspace at: $ROOT"

# --- Python cache directories (recursive, anywhere in the tree) -------
# `-prune` stops `find` from descending into a directory it has matched
# (we're about to delete it, so descending would error). `+` batches
# arguments per `rm -rf` invocation.
for d in '__pycache__' '.pytest_cache' '.ruff_cache' '.mypy_cache' 'htmlcov'; do
  find . -type d -name "$d" -not -path './.git/*' -prune -exec rm -rf {} + 2>/dev/null || true
done
find . -type d -name '*.egg-info' -not -path './.git/*' -prune -exec rm -rf {} + 2>/dev/null || true

# --- Coverage data files ----------------------------------------------
rm -fv .coverage .coverage.* coverage.xml 2>/dev/null || true

# --- Python build / wheel artifacts -----------------------------------
rm -rfv build/ dist/ wheels/

# --- MkDocs render output ---------------------------------------------
# Site is regenerated by `mkdocs build` (and by the docs.yml workflow).
rm -rfv site/

# --- Rust target tree -------------------------------------------------
# Regenerated by `maturin develop --release` or `cargo build`.
rm -rfv rust/target/

# --- Benchmark outputs ------------------------------------------------
# Logs, JSON results, and per-corpus generated DuckDB / SQLite stores.
# Inputs live under benchmarks/data/ and are NOT touched.
rm -rfv benchmarks/out/

echo "==> Workspace clean."
